name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest # Käytetään standardia CI-ympäristöä
    steps:
      - uses: actions/checkout@v4 # Haetaan koodi repositoriosta

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend dependencies
        working-directory: ./frontend
        run: npm install
      
      - name: Build And Preview
        working-directory: ./frontend
        run: | 
          npm run build
          npm run preview &
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pytest pytest-playwright
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ensure browsers are installed
        run: |
          playwright install --with-deps chromium # Asentaa selaimen ja linux-kirjastot

      - name: Run Playwright tests
        run: |
          # Asenna työkalu odottamiseen
          npx wait-on http://127.0.0.1:5173 --timeout 50000
          python pw_tests/test_login.py
        env:
          BASE_URL: http://127.0.0.1:5173
          APP_USERNAME: ${{ secrets.APP_USERNAME }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          CI: true

      - name: Upload Test Report
        if: always() # Ajetaan vaikka testit epäonnistuisivat
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30