name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Pytests (with Mocking)
        run: python -m pytest -v -s pytests/

  playwright-e2e:
    needs: backend-unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend dependencies
        working-directory: ./frontend
        run: npm install
      
      - name: Build And Preview
        working-directory: ./frontend
        env:
          VITE_API_URL: "http://127.0.0.1:5000"
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        run: | 
          npm run build
          npx vite preview --port 4173 --host 127.0.0.1 &
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pytest pytest-playwright
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ensure browsers are installed
        run: |
          playwright install --with-deps chromium # Asentaa selaimen ja linux-kirjastot

      - name: Run Playwright tests
        run: |
          curl -v http://127.0.0.1:4173 || echo "Palvelin ei vastaa viel√§"
          npx wait-on http://127.0.0.1:4173 --timeout 50000
          pytest pw_tests/ --tracing=retain-on-failure
        env:
          BASE_URL: http://127.0.0.1:4173
          APP_USERNAME: ${{ secrets.APP_USERNAME }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          CI: true

      - name: Upload Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/
          retention-days: 30